### ISSUE TITLE
База данных

### ISSUE THREAD

**Issue by pandanax** [pandanax/micro#21]
Подключить БД и перевести котов на БД

**Comment by pandanax** [comment]
**docker-compose.yml** example:

```
version: '3'

services:
  nestjs_app:
    build:
      context: ../micro
      dockerfile: ../micro/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URI=mongodb://mongodb:27017/test
    depends_on:
      - mongodb
    networks:
      - nest_network

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: test
    networks:
      - nest_network
    volumes:
      - ./db:/data/db

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - nest_network
    ports:
      - "8888:8081"

networks:
  nest_network:
    driver: bridge
```
